name: 'govulncheck as Github Action'
description: 'Run Go vulerability checker'
author: '@danielandersson'
inputs:
  args:
    description: 'Arguments for govulncheck'
    required: false
    default: './...'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}

branding:
  icon: 'alert-triangle'
  color: 'red'
